### ISSUE TITLE
its broken

### ISSUE THREAD

**Issue by miegl** [jovanlanik/wip#2]
![image](https://user-images.githubusercontent.com/24298857/159561628-5c205efa-2d48-4967-a95b-dc8942624144.png)
![image](https://user-images.githubusercontent.com/24298857/159561666-4a45ffd4-1e51-4693-a622-df1408cb5147.png)

**Comment by jovanlanik** [comment]
I don't see any issue. Can you describe the expected behavior?

**Comment by miegl** [comment]
Pressing `ESC` whilst Help is shown shouldn't get rid of world rendering. The same issue occurs when pressing the `ESC` key whilst informational messages from books are displayed.
